gui/base/controllers/account_settings.py
from flask import (Blueprint,
                   render_template,
                   flash, request,
                   redirect,
                   url_for,
                   session)
from flask.ext.login import login_required
from base.forms import SecretForm
import base

config = base.config
account_settings = Blueprint('account_settings', __name__)


@account_settings.route('/')
@login_required
def _account_settings():
    form = SecretForm()
    return render_template('account_settings.html', form = form)
    

gui/base/controllers/dashboard.py
import json

from flask import (Blueprint,
                   Response,
                   render_template,
                   flash,
                   request,
                   redirect,
                   url_for,
                   session,
                   jsonify)
from flask.ext.login import (login_user,
                             logout_user,
                             login_required,
                             current_user)
import base
from base import cache
from base.forms import LoginForm, NewExperimentForm, NewProjectForm
from base.models import User
from base.current import *
import base.settings

config = base.settings.Config()
dashboard = Blueprint('dashboard', __name__)

@dashboard.route('/')
@login_required
def _dashboard():
        if (not current_user.aws_bucket_name or
            not current_user.access_key_id or
            not current_user.secret_access_key or
            not current_user.next_backend_global_host):   
                return redirect(url_for('setup._setup'))
        else:
                return render_template('dashboard.html')

@dashboard.route('/edit_project/<project_id>', methods=["GET","POST"])
@login_required
def edit_project(project_id):
	# need to set current project before editing it
	set_project(project_id = project_id)
	return redirect(url_for('project.edit', project_id=project_id))

@dashboard.route('/delete_project/<project_id>', methods=["GET","POST"])
@login_required
def delete_project(project_id):
	# need to set current project before deleting it
	set_project(project_id = project_id)
	return redirect(url_for('project.delete', project_id=project_id))

gui/base/controllers/experiment.py
import csv, json, os, requests
from bson.json_util import dumps
from flask import Blueprint, Response, render_template, flash, request, redirect, url_for, session,jsonify
from flask.ext.login import login_user, logout_user, login_required, current_user
from flask_wtf import Form
from wtforms import TextField, PasswordField, TextAreaField, RadioField, FieldList, IntegerField, FormField, validators
from werkzeug.local import Local

import base
from base import cache
from base.forms import LoginForm, NewExperimentForm, NewProjectForm
from base.models import User, Experiment
from base.current import *
from base.app_manager import app_manager

config = base.Config()
experiment = Blueprint('experiment', __name__)

@experiment.route('/<experiment_id>')
@login_required
@project_required
def _experiment(experiment_id):
    set_experiment(experiment_id=experiment_id)
    # Frontend base url needed for stats and widgets
    next_backend_url = "http://"+next_backend_global_host+":"+config.NEXT_BACKEND_GLOBAL_PORT
    # Frontend url needed for queries
    next_frontend_url = "http://"+config.NEXT_FRONTEND_GLOBAL_HOST+":"+config.NEXT_FRONTEND_GLOBAL_PORT
    # query the app_manager for app specific params
    app_resource = app_manager.get_app_resource(current_experiment.app_id)
    # This is an html string containing the necessary app dashboard.
    app_dashboard_html = app_resource.get_experiment_dashboard(current_experiment)
    return render_template('experiment.html',
                           experiment_id=experiment_id,
                           next_backend_url=next_backend_url,
                           next_frontend_url=next_frontend_url,
                           app_dashboard_html=app_dashboard_html)

@experiment.route('/clone/<experiment_id>',methods=["GET","POST"])
@login_required
@project_required
@experiment_required
def clone(experiment_id):
    set_experiment(experiment_id=experiment_id)
    # copy current experiment attributes
    app_id = current_experiment.app_id
    name = current_experiment.name + '_clone'
    description = current_experiment.description
    instructions = current_experiment.instructions
    debrief = current_experiment.debrief
    params  = current_experiment.params
    target_set = current_experiment.target_set
    # create new experiment object
    experiment = Experiment(name=name,
                            description = description,
                            instructions = instructions,
                            debrief = debrief,
                            app_id = app_id,
                            params=params,
                            target_set=target_set)
    experiment.save()
    # Add experiment to the current project
    current_project.add_experiment(experiment)
    return redirect(url_for('experiment.edit', experiment_id=experiment.id))

@experiment.route('/edit/<experiment_id>',methods=["GET","POST"])
@login_required
@project_required
@experiment_required
def edit(experiment_id):
    # initialize form with base form of NewExperimentForm
    class NewExperimentForm_params(NewExperimentForm):
        pass

    # query the app_manager for app specific params
    app_resource = app_manager.get_app_resource(current_experiment.app_id)

    # This is an html string containing the necessary app params.
    app_params_template, app_params_form = app_resource.get_experiment_params()

    # associate app_params_form to form.params
    NewExperimentForm_params.params = FormField(app_params_form)
    form = NewExperimentForm_params(obj=current_experiment)

    # render app params form template with the new composited form
    app_params_html = render_template(app_params_template, form=form.params)

    # Update the target set selections
    target_set_names = [target.name for target in current_project.target_sets]

    # Is exposing the target id a potential security hole?
    target_set_ids = [target.id for target in current_project.target_sets]
    form.target_set.choices = zip(target_set_ids, target_set_names)

    if form.validate_on_submit():
        # update all fields
        # Why do we use updates instead of saves?
        print form.params.data
        current_experiment.update(set__name=form.name.data)
        current_experiment.update(set__description=form.description.data)
        current_experiment.update(set__instructions=form.instructions.data)
        current_experiment.update(set__debrief = form.debrief.data)
        current_experiment.update(set__params=form.params.data)
        current_experiment.update(set__target_set=form.target_set.data)
        current_experiment.update(set__query_tries=form.query_tries.data)
        current_experiment.update(set__query_duration=form.query_duration.data)
        return redirect(url_for('experiment._experiment', experiment_id=current_experiment.id))

    return render_template("edit_experiment_details.html", form=form, app_params_html = app_params_html)


@experiment.route('/delete/<experiment_id>',methods=["GET","POST"])
@login_required
@project_required
@experiment_required
def delete(experiment_id):
    current_project.update(pull__experiments=experiment_id)
    Experiment.objects(id=experiment_id).delete()
    set_experiment()
    return redirect(url_for('project._project', project_id=current_project.id))

@experiment.route('/run_experiment/<experiment_id>')
@login_required
@project_required
@experiment_required
def run_experiment(experiment_id):
    # Get the appropriate app manager resource
    app_resource = app_manager.get_app_resource(current_experiment.app_id)
    # Run the experiment using this app resource
    url = "http://"+next_backend_global_host+":"+config.NEXT_BACKEND_GLOBAL_PORT+"/api/experiment"
    response_dict = app_resource.run_experiment(current_experiment, url)

    if 'exp_uid' in response_dict.keys() and 'exp_key' in response_dict.keys():
        current_experiment.set_exp_uid(response_dict['exp_uid'])
        current_experiment.set_exp_key(response_dict['exp_key'])
        current_experiment.set_perm_key(response_dict['perm_key'])
    else:
        flash("Failed to change experiment status to running.")
        return redirect(url_for('experiment._experiment', experiment_id = current_experiment.id))

    # Get the experiment info and store it in our current model
    response = requests.get(url+"/"+current_experiment.exp_uid+"/"+current_experiment.exp_key)
    current_experiment.set_info(eval(response.text))

    # Now that we have an exp_uid and exp_key, we can do the target mapping. This needs some error handling here.
    create_target_mapping_dict = {}
    create_target_mapping_dict['app_id'] = current_experiment.app_id
    create_target_mapping_dict['exp_uid'] = current_experiment.exp_uid
    create_target_mapping_dict['exp_key'] = current_experiment.exp_key

    # Do this more cleanly. The problem is that mongoengine fields can't be json serialized.
    create_target_mapping_dict['target_blob'] = [mongo_to_dict(doc) for doc in current_experiment.target_set.targets]
    url = "http://"+next_backend_global_host+":"+config.NEXT_BACKEND_GLOBAL_PORT+"/api/targets/createtargetmapping"
    response = requests.post(url,
                             json.dumps(create_target_mapping_dict),
                             headers={'content-type':'application/json'})
    # This should only be done if we can confirm that all the previous steps worked.
    current_experiment.set_status('running')
    return redirect(url_for('experiment._experiment', experiment_id = current_experiment.id))


@experiment.route('/get-temp-keys')
@login_required
@project_required
@experiment_required
def get_temp_keys():
    n = int(request.args.get("keys_count",0))
    # Use local links to to local request
    url = "http://"+next_backend_global_host+":"+config.NEXT_BACKEND_GLOBAL_PORT+"/api/temp-widget-keys"
    args = {
        'exp_uid':current_experiment.exp_uid,
        'exp_key':current_experiment.exp_key,
        'n': n,
        'tries': current_experiment.query_tries,
        'duration': current_experiment.query_duration
        }

    try:
        response = requests.post(url, json.dumps(args), headers={'content-type':'application/json'})
    except (requests.HTTPError, requests.ConnectionError) as e:
        print "Excepted in get_temp_key", e
        raise

    keys = eval(response.text)["keys"]
    # Use the global host and port since these are external links
    links = ["http://"+ config.NEXT_FRONTEND_GLOBAL_HOST+":"+str(config.NEXT_BACKEND_GLOBAL_PORT)+"/query/query_page/query_page/"+current_experiment.exp_uid+"/"+key for key in keys]
    return "\n".join(links),200, {'Content-Disposition':'attachment'}

@experiment.route('/get-participant-responses')
@login_required
@project_required
@experiment_required
def get_participant_responses():
    url = "http://"+next_backend_global_host+":"+config.NEXT_BACKEND_GLOBAL_PORT
    app_resource = app_manager.get_app_resource(current_experiment.app_id)
    participant_responses = app_resource.get_formatted_participant_data(current_experiment, url)
    return "\n".join(participant_responses), 200, {'Content-Disposition':'attachment', 'Content-Type': 'text/csv; charset=utf-8'}

@experiment.route('/get-embedding')
@login_required
@project_required
@experiment_required
def get_embedding():
    url = "http://"+next_backend_global_host+":"+config.NEXT_BACKEND_GLOBAL_PORT
    app_resource = app_manager.get_app_resource(current_experiment.app_id)
    embedding = app_resource.get_formatted_embedding_data(current_experiment,
                                                          url)
    print embedding

    return "\n".join(embedding), 200, {'Content-Disposition':'attachment', 'Content-Type': 'text/csv; charset=utf-8'}

#############################
# Some utility functions

def mongo_to_dict(doc):
    # This is a bit sloppy
    d = doc.to_mongo().to_dict()
    del d['_id']
    return d

@experiment.route('/query/<app_id>/<exp_uid>/<widget_key>')

gui/base/controllers/new_experiment.py
from flask import Blueprint, render_template, flash, request, redirect, url_for, session
from flask.ext.login import login_user, logout_user, login_required
from wtforms import TextField, PasswordField, TextAreaField, RadioField, FieldList, IntegerField, FormField, StringField, validators
from wtforms.compat import with_metaclass, iteritems, itervalues
from flask_wtf import Form

from base import cache
from base.forms import LoginForm, NewExperimentForm
from base.models import User
from base.current import *
from base.app_manager import app_manager

new_experiment = Blueprint('new_experiment', __name__)

@new_experiment.route('/')
@login_required
@project_required
def _new_experiment():
    # check to see if targets have been uploaded
    if len(current_project.target_sets) == 0:
        return render_template('no_targets.html')
    else:
        # targets have been uploaded, show new experiment page
        return render_template('new_experiment.html')

@new_experiment.route('/<app_id>',methods=["GET","POST"])
@login_required
@project_required
def new_experiment_details(app_id):

    # initialize form with base form of NewExperimentForm
    class NewExperimentForm_params(NewExperimentForm):
        pass

    # query the app_manager for app specific params
    app_resource = app_manager.get_app_resource(app_id)

    # This is an html string containing the necessary app params.
    app_params_template, app_params_form = app_resource.get_experiment_params()

    # associate app_params_form to form.params
    NewExperimentForm_params.params = FormField(app_params_form)
    form = NewExperimentForm_params()

    # Update the target set selections
    target_set_names = [target.name for target in current_project.target_sets]

    # Is exposing the target id a potential security hole?
    target_set_ids = [target.id for target in current_project.target_sets]
    form.target_set.choices = zip(target_set_ids, target_set_names)

    # check if form is validated
    if form.validate_on_submit():
        # do app specific processing, returns false if processing fails
        if form.params.process_experiment_params():
            name = form.name.data
            description = form.description.data
            instructions = form.instructions.data;
            debrief = form.debrief.data
            params  = form.params.data
            target_set = form.target_set.data
            query_tries = form.query_tries.data
            query_duration = form.query_duration.data
            experiment = Experiment(
                name=name,
                description = description,
                instructions = instructions,
                debrief = debrief,
                app_id = app_id,
                params=params,
                target_set=target_set,
                query_tries = query_tries,
                query_duration = query_duration
            )
            experiment.save()

            # Add experiment to the current project
            current_project.add_experiment(experiment)
            return redirect(url_for('experiment._experiment', experiment_id=experiment.id))

    # render app params form template with the new composited form
    app_params_html = render_template(app_params_template, form=form.params)
    return render_template("new_experiment_details.html", form=form, app_params_html=app_params_html)

gui/base/controllers/new_project.py
from flask import Blueprint, Response, render_template, flash, request, redirect, url_for, session,jsonify
import json
from flask.ext.login import login_user, logout_user, login_required, current_user
from base.current import *
from base import cache
from base.forms import LoginForm, NewProjectForm
from base.models import User, Project

new_project = Blueprint('new_project', __name__)

@new_project.route('/', methods=["POST","GET"])
@login_required
def _new_project():
	form = NewProjectForm()
	if form.validate_on_submit():
	    name = form.name.data
	    description = form.description.data
            print "project count", Project.objects(name = name).count()
            if Project.objects(name = name).count() ==0:
                    project = Project(name=name, description=description)
                    project.save()
                    project.add_user(current_user.to_dbref())
                    current_user.add_project(project)
                    return redirect(url_for("project._project", project_id = project.id))
            else:
                    flash("Project name already exists")
                    
	return render_template('new_project.html', form=form)

gui/base/templates/account_settings.html
{% extends "outline.html" %}

{%block style_include %}
<link rel="stylesheet" type="text/css" href="/static/css/datatable.min.css">
<link rel="stylesheet" type="text/css" href="/static/css/datatable-bootstrap.min.css"/>

{%endblock %}

{%block script_include %}
<script type="text/javascript" src="/static/js/bootstrap.min.js"></script>    
{%endblock %}

{% block title %} Account Settings {% endblock %}

{% block body %}
<h1 class="page-header">Account Settings</h1>

 
{% endblock %}  

gui/base/templates/experiment.html
{% extends "outline.html" %}

{% block javascript %}
<script type="text/javascript" src="/static/js/d3.js"></script>
<script type="text/javascript" src="/static/js/d3.tip.v0.6.3.js"></script>
<script type="text/javascript" src="/static/js/next_widget.js"></script>
<script type="text/javascript" src="/static/js/next_data.js"></script>
<script type="text/javascript" src="/static/js/charts2.js"></script>

<script>
  next_widget.setUrl("{{ next_backend_url }}")
</script>
{% endblock %}

{% block css %}
      <style type="text/css">
            .embedding {
                background-color: white;
                border-style                :   solid;
                border-width                :   3px;
                border-color                :   #C0C0C0;
                border-radius               :   3px;
                width                       :   800px;
                height                      :   500px;
            }

            .overlay {
                fill: none;
                pointer-events: all;
            }

            .tooltip {
                position: absolute;
                pointer-events: none;
                background-color: navy;
            }

	    .plot {
	    	width: 100%;
	    	height: 400px;
	    }


      </style>

{% endblock %}

{% block title %} Experiment {% endblock %}

{% block sidebar %}
{% include "_project_sidebar.html" %}
{% include "_experiment_sidebar.html" %}
{% endblock %}

{% block body %}

<h1 class="page-header">Experiment: {{ current_experiment.name }}</h1>

<div class="panel panel-default">
  <div class="panel-body">
   <p><b>Description:</b> {{ current_experiment.description }} </p>
{#
   <p><b>Parameters</b>  </p>
    <!--   Maybe make this a <ul>?
    <p><b>Instructions:</b> [generate instructions here] </p>
    <p><b>Debriefing:</b> [add debrief here] </p>
    <p><b>Target Set:</b> [add target set here] </p>

     <p><b>Query Number:</b> [add query value here] </p>
     <p><b>Duration:</b> [add duration value] </p>
     <p><b>Dimensions:</b> [dimension value] </p>
     <p><b>Confidence Level:</b> [conf value] </p>
     <p><b>Algorithms Used:</b> [add alg labels and proportions] </p>
     <p><b>Algorithm Management:</b> [add  value] </p>
     <p><b>Participant to Algorithm Management:</b> [add duration value] </p>
     -->
#}
  </div>
</div>

{% if current_experiment.status == "staging" %}
<div class="panel panel-default">
  <div class="panel-body">


    <p> <b> Status: </b> Staging</p>
    <p>  By clicking the button, you will change the experiment status to running. At that point, you will no longer be able to make any changes to the experiment. </p>

    <a class="btn btn-primary" href="{{ url_for('experiment.run_experiment', experiment_id = current_experiment.id) }}">Run Experiment</a>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <ul class=flashes>
      {% for message in messages %}
      <li>{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %}
    {% endwith %}

  </div>
</div>
{% else %}


<div class="panel panel-default">
  <div class="panel-body">
    <p> <b> Status:</b> Running</p>
    <p>
      <b>exp_uid:</b> {{ current_experiment.exp_uid }}
      <br>
      <b>exp_key:</b> {{ current_experiment.exp_key }}
      <br>
      <br>
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target='#info'>Detailed Info</button>

    <!-- Modal -->
    <div class="modal fade" id="info" tabindex="-1" role="dialog" aria-labelledby="directions" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h1 class="modal-title" id="directions">Detailed Info</h1>
          </div>
          <div class="modal-body">
            <p>{{ current_experiment.info.items() }}</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>

    <p> <b> Permanent Query View:</b> </p>
<!--     <div class="well well-sm col-lg-6" style="overflow:hidden;text-overflow:ellipsis;">
      <a href="{{ next_frontend_url }}/experiment/query/{{ current_experiment.app_id }}/{{ current_experiment.exp_uid }}/{{ current_experiment.perm_key }}" target="_blank">{{ next_frontend_url }}/experiment/query/{{ current_experiment.app_id }}/{{ current_experiment.exp_uid }}/{{ current_experiment.perm_key }}</a>
    </div> -->
    <div class="well well-sm col-lg-6" style="overflow:hidden;text-overflow:ellipsis;">
      <a href="{{ next_backend_url }}/query/query_page/query_page_popup/{{ current_experiment.exp_uid }}/{{ current_experiment.perm_key }}" target="_blank">{{ next_backend_url }}/query/query_page/query_page_popup/{{ current_experiment.exp_uid }}/{{ current_experiment.perm_key }}</a>
    </div>
{#    <div class="col-lg-12" style="padding:0">
      <p> <b> Temporary Query View (Experimental): </b> </p>
      <div class="input-group col-lg-6">
      	<input type="text" name="keys_count" class="form-control" id="keys_count_form" oninput="outputUpdate(value)" placeholder="Enter desired number of temporary query view">
      	<span class="input-group-btn">
      	  <a href="get-temp-keys?keys_count=50" id="keys_count_button" download="keys.txt"><button type="button" class="btn btn-default" > Generate Keys </button></a>
      	</span>
      </div> #}
      <script>
      	<!-- Replace this with a get at some point a-->
      	function outputUpdate(value) {
      	$("#keys_count_button").attr("href", "get-temp-keys?keys_count="+value.toString() );
      	}
      </script>
    </div>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-body">
    <p><b>Results</b></p>
    The results are available on the backend:
    <p></p>
    <div class="well well-sm col-lg-6" style="overflow:hidden;text-overflow:ellipsis;">
        <a href="{{ next_backend_url }}/dashboard/experiment_dashboard/{{current_experiment.exp_uid}}/{{current_experiment.app_id}}/{{current_experiment.exp_key}}">
            {{ next_backend_url }}/dashboard/experiment_dashboard/{{current_experiment.exp_uid}}/{{current_experiment.app_id}}/{{current_experiment.exp_key}}
        </a>
    </div>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-body">
    <p><b>Participant Responses</b></p>
    Get participant response data as a CSV file.
    <p></p>
    <div class="well well-sm col-lg-6" style="overflow:hidden;text-overflow:ellipsis;">
        <a href="get-participant-responses" download="participant-responses.csv">participant-responses.csv</a>
    </div>
    <div class="col-lg-6">
    This file includes
    <ul>
        <li>Participant IDs</li>
        <li>Timestamps</li>
        <li>Images displayed</li>
        <li>Answers</li>
        <li>Response time (s)</li>
    </ul>
  </div>
  </div>
</div>

{{ app_dashboard_html|safe }}

{% endif %}
{% endblock %}

gui/base/templates/new_experiment.html
{% extends "outline.html" %}

{% block title %} New Experiment {% endblock %}

{% block sidebar %}
{% include "_project_sidebar.html" %}
{% endblock %}

{% block body %}

<h1 class="page-header">New Experiment</h1>
<div>
  <div class="description">First you need to decide what type of experiment you would like to create:</div>
  <table>
    <tbody>
      <tr style="height:145px">
        <td class="col-sm-1 text-center">
            <a href="{{ url_for('new_experiment.new_experiment_details', app_id='PoolBasedTripletMDS') }}">
          <img style="border:1px solid; max-width:100px" src="/static/img/triplet.jpg"></img>
            </a>
        </td>
        <td class="col-sm-6" style="vertical-align:top;">
          <h2 class="sub-header">
            <a href="{{ url_for('new_experiment.new_experiment_details', app_id='PoolBasedTripletMDS') }}">Triplet Experiment</a>
          </h2>
      	  <div class="description" style="text-align: left; width:70%;">
      	    Triplet experiments compare one item (A) to two other items (B & C) for similarity. A complex mathematical algorithm is used to calculate the distance between all items in the set, providing a measure of relationships between the items.
      	  </div>
        </td>
      </tr>
      <tr style="height:145px">
        <td class="col-sm-2 text-center">
            <a href="{{ url_for('new_experiment.new_experiment_details', app_id='DuelingBanditsPureExploration') }}">
          <img style="border:1px solid; max-width:100px" src="/static/img/Dueling.jpg"></img>
            </a>
        </td>
        <td class="col-sm-6" style="vertical-align:top;">
          <h2 class="sub-header">
            <a href="{{ url_for('new_experiment.new_experiment_details', app_id='DuelingBanditsPureExploration') }}">
              Dueling Bandits Pure Exploration
            </a>
          </h2>
      	  <div class="description" style="text-align: left;">
      	    Compare 2 items.
      	  </div>
        </td>
      </tr>

{#
      <tr style="height:145px">
        <td class="col-sm-2 text-center">
          <img style="border:1px solid; max-width:100px" src="/static/img/Tuple.jpg"></img>
        </td>
        <td class="col-sm-6" style="vertical-align:top;">
          <h2 class="sub-header">
            <a href="{{ url_for('new_experiment.new_experiment_details', app_id='TupleBanditsPureExploration') }}">
              Tuple Bandits Pure Exploration
            </a>
          </h2>
          <div class="description" style="text-align: left;">
            Compare k items.
          </div>
        </td>
      </tr>
#}
    </tbody>
  </table>
</div>
{% endblock %}

gui/base/templates/outline.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>NEXT.Discovery {% block title %}  {% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
        
    <!-- css -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link href="/static/css/content.css" rel="stylesheet">
    <link href="/static/css/metisMenu.min.css" rel="stylesheet">
    <link href="/static/css/sb-admin-2.css" rel="stylesheet">
    <link href="/static/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    {% block css %} {% endblock %}

    <!-- javascript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js" defer></script>
    <script type="text/javascript" src="/static/js/metisMenu.min.js" defer></script>
    <script type="text/javascript" src="/static/js/sb-admin-2.js" defer></script>
    {% block javascript %} {% endblock %}

</head>

<body>
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-custom navbar-static-top top-nav-collapse" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.home') }}">
                    <!-- <img class="next-square-logo" src="../static/images/next-logo-white.png" alt="" height="42" width="42"/> -->
                    <span class="next-logo-front">NEXT</span>
                    <span class="discovery-logo">.discovery</span>
                </a>
            </div>
            <!-- /.navbar-header -->

            <div class="collapse navbar-collapse navbar-right navbar-main-collapse" style="margin-right:0">
                <ul class="nav navbar-nav">
                    {% if current_user.is_authenticated() %}
                    <li><a href="{{ url_for('main.home') }}">Home</a></li>
                    <li><a href="{{ url_for('setup._setup') }}">Settings</a>
		    <li><a href="{{ url_for('main.logout') }}">Logout</a></li>
                    {% endif %}
                </ul>
            </div>
            <!-- /.navbar-top-links -->

            <!-- sidebar -->
            <div class="navbar-custom sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <!-- dashboard -->
                        <li>
                            <a href="{{ url_for('dashboard._dashboard') }}"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>

                        <li>
                            <a href="{{ url_for('new_project._new_project') }}"><i class="fa fa-plus fa-fw"></i> New Project</a>
                        </li>
                        {% block sidebar %} {% endblock %}
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    {% block body %} {% endblock %}
                </div>
                <!-- /.col-lg-12 -->
            </div>
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- Metis-menu script -->
    <script>
        $(function () {
            $('#side-menu').metisMenu({ 
            });
        });
    </script>

</body>

</html>

gui/base/templates/test_form.html
<html>
  <p> test form</p>

<form method="POST" id="form">
    <div>{{ form.name.label }}: {{ form.name }}</div>
    <div>{{ form.value.label }}: {{ form.value }}</div>
    <div>{{ form.custom.label }}: {{ form.custom }}</div>
    <button type="submit">Submit</button>
</form>


</html>